In [4]:
import numpy as np

# Ex 12-2

TD:

```
delta_w = learning_rate * (immediate_reward + disccount_factor * Us' - Us) * Xs
```

In [5]:
learning_rate = 0.1
disccount_factor = 0.9

x_s = np.array([
    # six upper states
    [2,0,0,0,0,0,0,1],
    [0,2,0,0,0,0,0,1],
    [0,0,2,0,0,0,0,1],
    [0,0,0,2,0,0,0,1],
    [0,0,0,0,2,0,0,1],
    [0,0,0,0,0,2,0,1],

    # seventh state
    [0,0,0,0,0,0,1,7],
], dtype='float64')
U_s = np.zeros((7,1))
R_s = np.zeros((7,1))
w = np.array([1,1,1,1,1,1,1,1], dtype='float64')

round = 1
for state in range(0, 7*round):
    current_state = state%7
    print('current state: ', current_state+1)
    # evaluation
    U_s[current_state] = np.sum(np.multiply(x_s[current_state], w))
    U_s[6] = np.sum(np.multiply(x_s[6], w))
    print('delta: ', (R_s[current_state] + disccount_factor * U_s[6] 
                      - U_s[current_state]), f' * x_{current_state+1}')
    # control
    w += learning_rate * (R_s[current_state] + disccount_factor * U_s[6] 
                          - U_s[current_state]) * x_s[current_state]
    print(w)
    print('------------\n')

current state:  1
delta:  [4.2]  * x_1
[1.84 1.   1.   1.   1.   1.   1.   1.42]
------------

current state:  2
delta:  [6.426]  * x_2
[1.84   2.2852 1.     1.     1.     1.     1.     2.0626]
------------

current state:  3
delta:  [9.83178]  * x_3
[1.84     2.2852   2.966356 1.       1.       1.       1.       3.045778]
------------

current state:  4
delta:  [15.0426234]  * x_4
[1.84       2.2852     2.966356   4.00852468 1.         1.
 1.         4.55004034]
------------

current state:  5
delta:  [23.0152138]  * x_5
[1.84       2.2852     2.966356   4.00852468 5.60304276 1.
 1.         6.85156172]
------------

current state:  6
delta:  [35.21327712]  * x_6
[ 1.84        2.2852      2.966356    4.00852468  5.60304276  8.04265542
  1.         10.37288943]
------------

current state:  7
delta:  [-7.3610226]  * x_7
[1.84       2.2852     2.966356   4.00852468 5.60304276 8.04265542
 0.26389774 5.22017361]
------------

